name = input('Enter your first name: ')
last_name = input('Enter your last name: ')
phone = input('Enter your phone number: ')
street = input('Enter your street name:')
house = input('Enter your house number:')
flat = input('Enter your flat number:')
city = input('Enter your city:')
index = input('Enter your index:')
country = input('Enter your country:')
#частина яка вводиться користувачем
print(name , last_name)
print(phone)
print('Str', street, house, 'ap', flat, ',', city)
print(index)
print(country)
#частина яка виводиться на екран